# Homebrew Bundle file: https://github.com/Homebrew/homebrew-bundle
# Homebrew Cask setup
cask_args appdir: "/Applications"
tap "homebrew/cask"
# Mac App Store cli: https://github.com/mas-cli/mas
brew "mas"

brew "python"
cask "alacritty"
brew "awscli"
brew "aws-iam-authenticator"
cask "aws-vault"
cask "authy"
brew "bash"
brew "bash-completion@2"
cask "docker"
brew "git"
brew "golang"
cask "google-chrome"
brew "kubectl"
brew "kubectx"
brew "kubeseal"
brew "neovim"
cask "postman"
cask "slack"
cask "spotify"
cask "sqlpro-for-postgres"
brew "terraform"
brew "vault"
cask "viscosity"
cask "zoomus"
