# Font
## To get a full list of supported fonts use the `kitty +list-fonts` command.
font_family JetBrains Mono NL
italic_font auto
bold_italic_font auto
font_size 14.0

# window settings
remember_window_size yes
initial_window_width  640
initial_window_height 400

# transparency
background_opacity 0.9

## To list all kitty themes use the `kitty +kitten themes` command
## To apply a theme use the `kitty +kitten themes --reload-in=all <theme>` command

# BEGIN_KITTY_THEME
# Rosé Pine Moon
include current-theme.conf
# END_KITTY_THEME
