#!/usr/bin/env bash

# Variables
GITHUB_REPO="dawilliams/dotfiles"
LOCAL_REPO=".dotfiles"

# Use https because ssh may not be set up yet.
git clone --bare https://github.com/$GITHUB_REPO.git "$HOME"/$LOCAL_REPO

# define config alias locally since the dotfiles
# aren't installed on the system yet
function dot {
   git --git-dir="$HOME"/$LOCAL_REPO/ --work-tree="$HOME" "$@"
}

# create a directory to backup existing dotfiles to
mkdir -p $LOCAL_REPO-backup
dot checkout

if [ $? = 0 ]; then
  echo "Checked out $LOCAL_REPO from https://github.com/$GITHUB_REPO.git";
  #dot config status.showUntrackedFiles no
  else
    mkdir -p $LOCAL_REPO-backup
    echo "Github bare repository checkout failed. Move any existing dotfiles to ~/$LOCAL_REPO-backup";
fi
