# includes
## Need to install this based on instructions at https://github.com/craffate/papercolor-kitty
include papercolor-kitty/papercolor-dark.conf

# fonts
font_family      SF Mono Regular
bold_font        SF Mono Bold
italic_font      SF Mono Regular Italic
bold_italic_font SF Mono Regular Bold Italic
font_size        16.0
