#!/usr/bin/env bash

# Variables
GITHUB_REPO="dawilliams/dotfiles"
LOCAL_REPO=".dotfiles"

# Use https because ssh may not be set up yet.
git clone --bare https://github.com/$GITHUB_REPO.git "$HOME"/$LOCAL_REPO

# define config alias locally since the dotfiles
# aren't installed on the system yet
function dot {
   git --git-dir="$HOME"/$LOCAL_REPO/ --work-tree="$HOME" "$@"
}

# create a directory to backup existing dotfiles to
mkdir -p $LOCAL_REPO-backup
dot checkout

if [ $? = 0 ]; then
  echo "Checked out $LOCAL_REPO from https://github.com/$GITHUB_REPO.git";
  else
    echo "Moving existing $LOCAL_REPO to ~/$LOCAL_REPO-backup";
    dot checkout 2>&1 | grep -e "\s+\." | awk {'print $1'} | xargs -I{} mv {} $LOCAL_REPO-backup/{}
fi

# checkout dotfiles from repo
dot checkout
#dot config status.showUntrackedFiles no
